from collections import defaultdict
import sys
import json
import glob

eventmap = {
"RunPass/AArch64 Assembly Printer": "LLVM_AsmPrinter",
"RunPass/AArch64 Branch Targets": "LLVM_OtherPasses",
"RunPass/AArch64 Instruction Selection": "LLVM_ISel",
"RunPass/AArch64 Pointer Authentication": "LLVM_OtherPasses",
"RunPass/AArch64 Stack Tagging": "LLVM_PreISel",
"RunPass/AArch64 pseudo instruction expansion pass": "LLVM_OtherPasses",
"RunPass/AArch64 sls hardening pass": "LLVM_OtherPasses",
"RunPass/AArch64 speculation hardening pass": "LLVM_OtherPasses",
"RunPass/AArch64O0PreLegalizerCombiner": "LLVM_ISel",
"RunPass/AArch64PostLegalizerLowering": "LLVM_ISel",
"RunPass/Analysis containing CSE Info": "LLVM_OtherPasses",
"RunPass/Analysis for ComputingKnownBits": "LLVM_OtherPasses",
"RunPass/Branch relaxation pass": "LLVM_OtherPasses",
"RunPass/Dominator Tree Construction": "LLVM_OtherPasses",
"RunPass/IRTranslator": "LLVM_ISel",
"RunPass/Implement the 'patchable-function' attribute": "LLVM_OtherPasses",
"RunPass/Insert CFI remember/restore state instructions": "LLVM_OtherPasses",
"RunPass/InstructionSelect": "LLVM_ISel",
"RunPass/Lazy Block Frequency Analysis": "LLVM_OtherPasses",
"RunPass/Lazy Branch Probability Analysis": "LLVM_OtherPasses",
"RunPass/Legalizer": "LLVM_ISel",
"RunPass/Localizer": "LLVM_ISel",
"RunPass/Natural Loop Information": "LLVM_OtherPasses",
"RunPass/Optimization Remark Emitter": "LLVM_OtherPasses",
"RunPass/RegBankSelect": "LLVM_ISel",
"RunPass/ResetMachineFunction": "LLVM_OtherPasses",
"RunPass/SME ABI Pass": "LLVM_PreISel",
"RunPass/Workaround A53 erratum 835769 pass": "LLVM_OtherPasses",
"RunPass/Expand large div/rem": "LLVM_PreISel",
"RunPass/Expand large fp convert": "LLVM_PreISel",
"RunPass/Expand Atomic instructions": "LLVM_PreISel",
"RunPass/Lower AMX intrinsics": "LLVM_PreISel",
"RunPass/Lower AMX type for load/store": "LLVM_PreISel",
"RunPass/Module Verifier": "LLVM_PreISel",
"RunPass/Lower Garbage Collection Instructions": "LLVM_PreISel",
"RunPass/Shadow Stack GC Lowering": "LLVM_PreISel",
"RunPass/Remove unreachable blocks from the CFG": "LLVM_PreISel",
"RunPass/Instrument function entry/exit with calls to e.g. mcount() (post inlining)": "LLVM_PreISel",
"RunPass/Scalarize Masked Memory Intrinsics": "LLVM_PreISel",
"RunPass/Expand reduction intrinsics": "LLVM_PreISel",
"RunPass/Expand indirectbr instructions": "LLVM_PreISel",
"RunPass/Exception handling preparation": "LLVM_PreISel",
"RunPass/Prepare callbr": "LLVM_PreISel",
"RunPass/Safe Stack instrumentation pass": "LLVM_PreISel",
"RunPass/Insert stack protectors": "LLVM_PreISel",
"RunPass/Assignment Tracking Analysis": "LLVM_PreISel",
"RunPass/X86 DAG->DAG Instruction Selection": "LLVM_ISel",
"RunPass/X86 PIC Global Base Reg Initialization": "LLVM_ISel",
"RunPass/Argument Stack Rebase": "LLVM_ISel",
"RunPass/Finalize ISel and expand pseudo-instructions": "LLVM_ISel",
"RunPass/Local Stack Slot Allocation": "LLVM_OtherPasses",
"RunPass/X86 speculative load hardening": "LLVM_OtherPasses",
"RunPass/X86 EFLAGS copy lowering": "LLVM_OtherPasses",
"RunPass/X86 DynAlloca Expander": "LLVM_OtherPasses",
"RunPass/Fast Tile Register Preconfigure": "LLVM_RA",
"RunPass/Eliminate PHI nodes for register allocation": "LLVM_RA",
"RunPass/Two-Address instruction pass": "LLVM_RA",
"RunPass/Fast Register Allocator": "LLVM_RA",
"RunPass/Fast Tile Register Configure": "LLVM_RA",
"RunPass/X86 Lower Tile Copy": "LLVM_OtherPasses",
"RunPass/Bundle Machine CFG Edges": "LLVM_OtherPasses",
"RunPass/X86 FP Stackifier": "LLVM_OtherPasses",
"RunPass/Remove Redundant DEBUG_VALUE analysis": "LLVM_OtherPasses",
"RunPass/Fixup Statepoint Caller Saved": "LLVM_OtherPasses",
"RunPass/Lazy Machine Block Frequency Analysis": "LLVM_OtherPasses",
"RunPass/Machine Optimization Remark Emitter": "LLVM_OtherPasses",
"RunPass/Prologue/Epilogue Insertion & Frame Finalization": "LLVM_OtherPasses",
"RunPass/Post-RA pseudo instruction expansion pass": "LLVM_OtherPasses",
"RunPass/X86 pseudo instruction expansion pass": "LLVM_OtherPasses",
"RunPass/Insert KCFI indirect call checks": "LLVM_OtherPasses",
"RunPass/Analyze Machine Code For Garbage Collection": "LLVM_OtherPasses",
"RunPass/Insert fentry calls": "LLVM_OtherPasses",
"RunPass/Insert XRay ops": "LLVM_OtherPasses",
"RunPass/Implement the 'patchable-function' attribute": "LLVM_OtherPasses",
"RunPass/X86 Indirect Branch Tracking": "LLVM_OtherPasses",
"RunPass/X86 vzeroupper inserter": "LLVM_OtherPasses",
"RunPass/Compressing EVEX instrs when possible": "LLVM_OtherPasses",
"RunPass/X86 Discriminate Memory Operands": "LLVM_OtherPasses",
"RunPass/X86 Insert Cache Prefetches": "LLVM_OtherPasses",
"RunPass/X86 insert wait instruction": "LLVM_OtherPasses",
"RunPass/Contiguously Lay Out Funclets": "LLVM_OtherPasses",
"RunPass/Remove Loads Into Fake Uses": "LLVM_OtherPasses",
"RunPass/StackMap Liveness Analysis": "LLVM_OtherPasses",
"RunPass/Live DEBUG_VALUE analysis": "LLVM_OtherPasses",
"RunPass/Machine Sanitizer Binary Metadata": "LLVM_OtherPasses",
"RunPass/Stack Frame Layout Analysis": "LLVM_OtherPasses",
"RunPass/X86 Speculative Execution Side Effect Suppression": "LLVM_OtherPasses",
"RunPass/X86 Indirect Thunks": "LLVM_OtherPasses",
"RunPass/X86 Return Thunks": "LLVM_OtherPasses",
"RunPass/Check CFA info and insert CFI instructions if needed": "LLVM_OtherPasses",
"RunPass/X86 Load Value Injection (LVI) Ret-Hardening": "LLVM_OtherPasses",
"RunPass/Pseudo Probe Inserter": "LLVM_OtherPasses",
"RunPass/Unpack machine instruction bundles": "LLVM_OtherPasses",
"RunPass/X86 Assembly Printer": "LLVM_AsmPrinter",
"RunPass/Free MachineFunction": "LLVM_OtherPasses",
"RunPass/Local Stack Slot Allocation": "LLVM_PreRA",
"RunPass/X86 speculative load hardening": "LLVM_PreRA",
"RunPass/X86 EFLAGS copy lowering": "LLVM_PreRA",
"RunPass/X86 DynAlloca Expander": "LLVM_PreRA",
"RunPass/X86 Lower Tile Copy": "LLVM_PostRA",
"RunPass/Bundle Machine CFG Edges": "LLVM_PostRA",
"RunPass/X86 FP Stackifier": "LLVM_PostRA",
"RunPass/Remove Redundant DEBUG_VALUE analysis": "LLVM_PostRA",
"RunPass/Fixup Statepoint Caller Saved": "LLVM_PostRA",
"RunPass/Lazy Machine Block Frequency Analysis": "LLVM_PostRA",
"RunPass/Machine Optimization Remark Emitter": "LLVM_PostRA",
"RunPass/Prologue/Epilogue Insertion & Frame Finalization": "LLVM_PostRA",
"RunPass/Post-RA pseudo instruction expansion pass": "LLVM_PostRA",
"RunPass/X86 pseudo instruction expansion pass": "LLVM_PostRA",
"RunPass/Insert KCFI indirect call checks": "LLVM_PostRA",
"RunPass/Analyze Machine Code For Garbage Collection": "LLVM_PostRA",
"RunPass/Insert fentry calls": "LLVM_PostRA",
"RunPass/Insert XRay ops": "LLVM_PostRA",
"RunPass/Implement the 'patchable-function' attribute": "LLVM_PostRA",
"RunPass/X86 Indirect Branch Tracking": "LLVM_PostRA",
"RunPass/X86 vzeroupper inserter": "LLVM_PostRA",
"RunPass/Compressing EVEX instrs when possible": "LLVM_PostRA",
"RunPass/X86 Discriminate Memory Operands": "LLVM_PostRA",
"RunPass/X86 Insert Cache Prefetches": "LLVM_PostRA",
"RunPass/X86 insert wait instruction": "LLVM_PostRA",
"RunPass/Contiguously Lay Out Funclets": "LLVM_PostRA",
"RunPass/Remove Loads Into Fake Uses": "LLVM_PostRA",
"RunPass/StackMap Liveness Analysis": "LLVM_PostRA",
"RunPass/Live DEBUG_VALUE analysis": "LLVM_PostRA",
"RunPass/Machine Sanitizer Binary Metadata": "LLVM_PostRA",
"RunPass/Stack Frame Layout Analysis": "LLVM_PostRA",
"RunPass/X86 Speculative Execution Side Effect Suppression": "LLVM_PostRA",
"RunPass/X86 Indirect Thunks": "LLVM_PostRA",
"RunPass/X86 Return Thunks": "LLVM_PostRA",
"RunPass/Check CFA info and insert CFI instructions if needed": "LLVM_PostRA",
"RunPass/X86 Load Value Injection (LVI) Ret-Hardening": "LLVM_PostRA",
"RunPass/Pseudo Probe Inserter": "LLVM_PostRA",
"RunPass/Unpack machine instruction bundles": "LLVM_PostRA",
"RunPass/Free MachineFunction": "LLVM_FreeMF",
"Total ExecuteCompiler": "total",
"Total Frontend": "frontend",
"Total Backend": "backend",
"Total CodeGenPasses": "codegen",
"Total TPDE": "codegen",
"Total Compile": "codegen",
"Total TPDE_Prepass": "prepass",
"Total TPDE_Analysis": "analysis",
"Total TPDE_CodeGen": "tpde_cg",
"Total TPDE_EmitObj": "emit_obj",
"Total TPDE_GlobalGen": "global_gen",
"Total TPDE_compute_precise_liveness": "tpde_pl",
"Total TPDE_compute_spills": "tpde_spill",
 # IR / pre-isel (frontend+midend / IR pipeline before instruction selection)
  "RunPass/Basic Alias Analysis (stateless AA impl)": "LLVM_PreISel",
  "RunPass/Canonicalize natural loops": "LLVM_PreISel",
  "RunPass/Scalar Evolution Analysis": "LLVM_PreISel",
  "RunPass/Loop Pass Manager": "LLVM_PreISel",
  "RunPass/Function Alias Analysis Results": "LLVM_PreISel",
  "RunPass/Merge contiguous icmps into a memcmp": "LLVM_PreISel",
  "RunPass/Expand memcmp() to load/stores": "LLVM_PreISel",
  "RunPass/Post-Dominator Tree Construction": "LLVM_PreISel",
  "RunPass/Branch Probability Analysis": "LLVM_PreISel",
  "RunPass/Block Frequency Analysis": "LLVM_PreISel",
  "RunPass/Constant Hoisting": "LLVM_PreISel",
  "RunPass/Replace intrinsics with calls to vector library": "LLVM_PreISel",
  "RunPass/Partially inline calls to library functions": "LLVM_PreISel",
  "RunPass/Interleaved Access Pass": "LLVM_PreISel",
  "RunPass/CodeGen Prepare": "LLVM_PreISel",
  "RunPass/ObjC ARC contraction": "LLVM_PreISel",

  # machine pre-regalloc
  "RunPass/MachineDominator Tree Construction": "LLVM_PreRA",
  "RunPass/Local Dynamic TLS Access Clean-up": "LLVM_PreRA",
  "RunPass/X86 Domain Reassignment Pass": "LLVM_PreRA",
  "RunPass/Early Tail Duplication": "LLVM_PreRA",
  "RunPass/Optimize machine instruction PHIs": "LLVM_PreRA",
  "RunPass/Remove dead machine instructions": "LLVM_PreRA",
  "RunPass/Machine Natural Loop Construction": "LLVM_PreRA",
  "RunPass/Machine Trace Metrics": "LLVM_PreRA",
  "RunPass/Early If-Conversion": "LLVM_PreRA",
  "RunPass/Machine InstCombiner": "LLVM_PreRA",
  "RunPass/X86 cmov Conversion": "LLVM_PreRA",
  "RunPass/Machine Block Frequency Analysis": "LLVM_PreRA",
  "RunPass/Early Machine Loop Invariant Code Motion": "LLVM_PreRA",
  "RunPass/Machine Common Subexpression Elimination": "LLVM_PreRA",
  "RunPass/MachinePostDominator Tree Construction": "LLVM_PreRA",
  "RunPass/Machine Cycle Info Analysis": "LLVM_PreRA",
  "RunPass/Machine code sinking": "LLVM_PreRA",
  "RunPass/Peephole Optimizations": "LLVM_PreRA",
  "RunPass/Detect Dead Lanes": "LLVM_PreRA",
  "RunPass/Init Undef Pass": "LLVM_PreRA",
  "RunPass/Process Implicit Definitions": "LLVM_PreRA",
  "RunPass/Remove unreachable machine basic blocks": "LLVM_PreRA",
  "RunPass/Machine Instruction Scheduler": "LLVM_PreRA",
  "RunPass/Machine Loop Invariant Code Motion": "LLVM_PreRA",
  "RunPass/Machine Dominance Frontier Construction": "LLVM_PreRA",
  "RunPass/Tail Duplication": "LLVM_PreRA",
  "RunPass/X86 Partial Reduction": "LLVM_PreRA",

  # regalloc (and closely related analyses/rewrites)
  "RunPass/Slot index numbering": "LLVM_RA",
  "RunPass/Merge disjoint stack slots": "LLVM_RA",
  "RunPass/Live Range Shrink": "LLVM_RA",
  "RunPass/Live Variable Analysis": "LLVM_RA",
  "RunPass/Live Interval Analysis": "LLVM_RA",
  "RunPass/Register Coalescer": "LLVM_RA",
  "RunPass/Rename Disconnected Subregister Components": "LLVM_RA",
  "RunPass/Debug Variable Analysis": "LLVM_RA",
  "RunPass/Live Stack Slot Analysis": "LLVM_RA",
  "RunPass/Virtual Register Map": "LLVM_RA",
  "RunPass/Live Register Matrix": "LLVM_RA",
  "RunPass/Spill Code Placement Analysis": "LLVM_RA",
  "RunPass/Greedy Register Allocator": "LLVM_RA",
  "RunPass/Virtual Register Rewriter": "LLVM_RA",
  "RunPass/Register Allocation Pass Scoring": "LLVM_RA",
  "RunPass/Stack Slot Coloring": "LLVM_RA",
  "RunPass/Tile Register Pre-configure": "LLVM_RA",
  "RunPass/Tile Register Configure": "LLVM_RA",

  # post-regalloc / late machine passes
  "RunPass/Machine Copy Propagation Pass": "LLVM_PostRA",
  "RunPass/X86 Load Value Injection (LVI) Load Hardening": "LLVM_PostRA",
  "RunPass/PostRA Machine Sink": "LLVM_PostRA",
  "RunPass/Shrink Wrapping analysis": "LLVM_PostRA",
  "RunPass/Machine Late Instructions Cleanup Pass": "LLVM_PostRA",
  "RunPass/Control Flow Optimizer": "LLVM_PostRA",
  "RunPass/Post RA top-down list latency scheduler": "LLVM_PostRA",
  "RunPass/Branch Probability Basic Block Placement": "LLVM_PostRA",
  "RunPass/ReachingDefAnalysis": "LLVM_PostRA",
  "RunPass/X86 Execution Dependency Fix": "LLVM_PostRA",
  "RunPass/BreakFalseDeps": "LLVM_PostRA",
  "RunPass/X86 Byte/Word Instruction Fixup": "LLVM_PostRA",
  "RunPass/X86 Atom pad short functions": "LLVM_PostRA",
  "RunPass/X86 LEA Fixup": "LLVM_PostRA",
  "RunPass/X86 Fixup Inst Tuning": "LLVM_PostRA",
  "RunPass/X86 Fixup Vector Constants": "LLVM_PostRA",
  "RunPass/X86 Windows Fixup Buffer Security Check": "LLVM_PostRA",
  "RunPass/X86 Fixup SetCC": "LLVM_PostRA",
  "RunPass/X86 LEA Optimize": "LLVM_PostRA",
  "RunPass/X86 Optimize Call Frame": "LLVM_PostRA",
  "RunPass/X86 Avoid Store Forwarding Blocks": "LLVM_PostRA",
}

if len(sys.argv) != 7:
    print('Usage: parse_trace_jsons.py <benchmarknum> <clang_O0_build_dir> <clang_O1_build_dir> <tpde_build_dir> <tpde_old_build_dir> <llc_mode>')
    exit(1)

benchmark = sys.argv[1]
clang_O0_path = sys.argv[2]
clang_O1_path = sys.argv[3]
tpde_path = sys.argv[4]
tpde_old_path = sys.argv[5]
llc_mode = (sys.argv[6] == 'true')
if llc_mode:
    eventmap["Total OptModule"] = "codegen"


def parse_jsons(folder_path, index):
    res = defaultdict(float)
    for filename in glob.glob(folder_path + f'/**/*.{index}.json', recursive=True):
        with open(filename) as f:
            content = json.load(f)
            for event in content['traceEvents']:
                name = event["name"]
                if name == "RunPass": name += "/" + event["args"]["detail"]
                group = eventmap.get(name)
                if not group and event["name"] == "RunPass":
                    print("WARNING: unmapped pass", event["args"]["detail"])
                    eventmap[name] = "LLVM_OtherPasses"
                if group:
                    res[group] += float(event["dur"])

    return res

for (ty, folder_path) in [('clang_o0', clang_O0_path), ('clang_o1', clang_O1_path), ('tpde', tpde_path), ('tpde_old', tpde_old_path)]:
    res = []
    for i in range(0, 5):
        res.append(parse_jsons(folder_path, i))

    res.sort(key=lambda r: r["total"])
    res = res[1:-1]
    for k in sorted(res[0].keys()):
        print(benchmark, k, ty, sum(r[k] for r in res) / len(res))
