#!/bin/bash
set -euo pipefail
set +x
compile=
args=("$@")
n=${#args[@]}
for ((i=0; i<n; ++i)); do
    case ${args[i]} in
        -o) output=${args[i+1]}; unset args[i]; unset args[i+1]; ((++i));;
        -c) compile=1;;
        -emit-llvm) compile=0;;
    esac
done
for ((i=0; i<5; ++i)); do
if [[ "$TPDE_LLC" == *"tpde-llc"* ]]; then
timetrace="--time-trace=$output.$i.json"
else
timetrace="--time-trace --time-trace-granularity=0 --time-trace-file=$output.$i.json"
fi
if [ -z $compile ]; then
    "${args[@]}" -o "$output"
else
    "${args[@]}" -emit-llvm -o - | $TPDE_LLC $timetrace -o "$output"
fi
done
